### ISSUE TITLE
Script produces invalid YAML

### ISSUE THREAD

**Issue by gerritholl** [loreclem/areadef#3]
Using the generator at http://clemspace.ch/areadef/ an example of YAML syntax I get is:

```yaml
saotome:
  description: São Tomé and Ilhéu das Rolas
    proj: eqc
    ellps: WGS84
    units: m
  shape:
    height: 565
    height: 684
  area_extent:
    lower_left_xy: [705505.3673684598, -11606.849730014801]
    upper_right_xy: [761962.8868997098, 56752.52526998521]
```

Trying to read this using `python -c 'import yaml, sys; print(yaml.safe_load(sys.stdin))' < areas.yaml` results in a `ScannerError`:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/yaml/constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/yaml/scanner.py", line 579, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<stdin>", line 3, column 9
```

Comparing with `satpy`-builtin `areas.yaml` files, it appears there should be a line `  projection:` immediately below the line starting with `  description:`.  If I add such a line, the YAML syntax appears correct (I can read it with `pyresample.area_config.load_area`).

**Comment by loreclem** [comment]
This seems to be fixed now, can you confirm?

**Comment by gerritholl** [comment]
Yes, this is fixed, thank you!
